name: Run Go Code
description: Execute Specified Go Files Code

inputs:
  go-file-paths:
    description: Comma Separated Go File Paths to Execute
    required: true 
    default: main.go

runs:
  using: docker
  image: mokhlesur96/custom-action:v2